blank_issues_enabled: false
contact_links:
  - name: Questions
    url: "https://github.com/any1/wayvnc/discussions"
    about: "Please ask questions on IRC in #wayvnc on Libera Chat or in Discussions"
