name: Build check

on:
  push:
    branches: [ "master", "ci-test" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: checkout aml
      uses: actions/checkout@v3
      with:
        repository: any1/aml
        path: subprojects/aml
    - name: checkout neatvnc
      uses: actions/checkout@v3
      with:
        repository: any1/neatvnc
        path: subprojects/neatvnc
    - name: setup
      run: sudo apt install -y meson libdrm-dev libxkbcommon-dev libwlroots-dev libjansson-dev libpam0g-dev libgnutls28-dev libavfilter-dev libavcodec-dev libavutil-dev libturbojpeg0-dev scdoc
    - name: configure
      run: meson build -D tests=true
    - name: make
      run: meson compile -C build
    - name: unit tests
      run: meson test  -C build
